language: java

sudo: false

jdk:
  - openjdk8

before_install:
  - chmod +x mvnw

script: mvn clean package

env:
  global:
    - JAVA_OPTS="-XX:+TieredCompilation -XX:TieredStopAtLevel=1 -Xmn48M -Xmx512M"
    - NUM_THREADS=2

